# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/src/client-admin-portal" # Location of package manifests
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/src/client-contractor-portal" # Location of package manifests
    schedule:
      interval: "weekly"
      
  - package-ecosystem: "pip"
    directory: "/" # Adjust if pyproject.toml or requirements.txt is in a subdirectory
    schedule:
      interval: "weekly"
